### PR TITLE
riscv-he: rebase 'master' onto riscv_hyp 

### PR DESCRIPTION
**Pull request by Ivan-Velickovic**
See SEL4PROJ/sel4-riscv-vmm-manifest#1 for details.

### CODE REVIEW

**Comment by lsf37** [comment]
Should this be a rebase rather than a merge? Rebase would need coordination with whoever is currently working on this, though. I believe @yyshen was looking into riscv-hyp.

**Comment by yyshen** [comment]
> Should this be a rebase rather than a merge? Rebase would need coordination with whoever is currently working on this, though. I believe @yyshen was looking into riscv-hyp.

@Ivan-Velickovic @lsf37 A rebase would be fine since I do not have recent changes.

**Comment by Ivan-Velickovic** [comment]
Okay, I think I've done the rebase. The DCO CI check is failing because 2b825554335aff440cadb952cf7c230438cf1a67 isn't signed off.

**Comment by Ivan-Velickovic** [comment]
Closed since it's not necessary for this to be a PR, it's only the rebase.

**Comment by yyshen** [comment]
> Okay, I think I've done the rebase. I think the DCO CI check is failing because [2b82555](https://github.com/seL4/seL4_libs/commit/2b825554335aff440cadb952cf7c230438cf1a67) isn't signed off, should @yyshen add the sign off?

Yes, I will add the signoff based on the rebase.

**Pull request closed without merging**
