### PR TITLE
trivial: typo

### PR DESCRIPTION
**Pull request by cvluca**

### CODE REVIEW

**Comment by xurtis** [comment]
Hi Luca, You'll need to sign off your commits before they can be merged. You can check out the [contribution guidelines](https://docs.sel4.systems/processes/contributing.html#developer-certificate-of-origin-dco) for specific details on what is required.

**Comment by cvluca** [comment]
> Hi Luca, You'll need to sign off your commits before they can be merged. You can check out the [contribution guidelines](https://docs.sel4.systems/processes/contributing.html#developer-certificate-of-origin-dco) for specific details on what is required.

That was a quick fix on GitHub. It seems signing off can only be done via the command line. Does the sign off is required for all the seL4 repos now?

**Comment by xurtis** [comment]
Yes, all commits in the `seL4` project require the DCO to be merged.

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by walle-whale** [comment]
Hi @cvluca could you please rebase on master.

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by axel-h** [comment]
Is there anything preventing the merge now?

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Pull request merged**
